# Generated by Django 3.1.4 on 2021-03-29 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_auto_20210329_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '"Статті'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='create_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='update_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор останнього оновлення'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_datetime',
            field=models.DateTimeField(verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_datetime',
            field=models.DateTimeField(verbose_name='Оновлено'),
        ),
    ]
