# Generated by Django 3.1.4 on 2021-03-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210329_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_photo',
            field=models.URLField(blank=True, null=True, verbose_name="Прев'ю фото"),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.URLField(blank=True, null=True, verbose_name="Прев'ю тексту"),
        ),
    ]
