# Generated by Django 3.1.4 on 2021-03-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210329_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_text',
            field=models.TextField(blank=True, null=True, verbose_name="Прев'ю тексту"),
        ),
    ]
