# Generated by Django 3.1.4 on 2021-04-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210330_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва')),
                ('url', models.URLField(blank=True, max_length=4096, null=True, verbose_name='Посилання')),
                ('tags', models.ManyToManyField(to='articles.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name_plural': 'Категорії статей',
            },
        ),
    ]
