# Generated by Django 3.1.4 on 2021-04-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_simplepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, max_length=4096, null=True, verbose_name='Посилання'),
        ),
    ]
