# Generated by Django 3.1.4 on 2021-04-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplepage',
            options={'verbose_name_plural': 'Прості сторінки'},
        ),
        migrations.AddField(
            model_name='simplepage',
            name='url',
            field=models.URLField(blank=True, max_length=4096, null=True, verbose_name='Посилання'),
        ),
    ]
