# Generated by Django 3.1.4 on 2021-04-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20210404_2015'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='articlecategory',
            table='article_category',
        ),
        migrations.AlterModelTable(
            name='simplepage',
            table='simple_page',
        ),
    ]
