# Generated by Django 3.1.4 on 2021-04-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20210404_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimplePage',
        ),
    ]
