# Generated by Django 3.1.4 on 2021-04-06 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_delete_simplepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
