# Generated by Django 3.2 on 2021-04-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20210412_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_hide',
            field=models.BooleanField(default=False, verbose_name='Сховати'),
        ),
    ]
