# Generated by Django 3.2 on 2021-04-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20210404_2209'),
        ('articles', '0021_article_is_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slider',
        ),
        migrations.CreateModel(
            name='ArticleSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Стаття')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.image', verbose_name='Світлина')),
            ],
            options={
                'verbose_name_plural': 'Слайдери статей',
                'db_table': 'article_slider',
            },
        ),
    ]
