# Generated by Django 3.2 on 2021-05-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20210404_2209'),
        ('articles', '0023_auto_20210529_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleslider',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.image', verbose_name='Слайд'),
        ),
    ]
