# Generated by Django 3.1.4 on 2021-03-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_navigation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Navigation',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категорії'},
        ),
    ]
