# Generated by Django 3.1.4 on 2021-03-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210321_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
