# Generated by Django 3.1.4 on 2021-03-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Світлина')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name_plural': 'Світлини',
            },
        ),
    ]
