# Generated by Django 3.1.4 on 2021-03-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Navigation',
        ),
        migrations.AlterModelOptions(
            name='navigation',
            options={'verbose_name_plural': 'Елементи навігації'},
        ),
    ]
